version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  grafana:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/config
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/config/prometheus.yml"

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SERVER_HTTP_PORT=3030
    depends_on:
      - prometheus
    ports:
      - "3030:3030"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      # - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards:/etc/grafana/dashboards
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    ports:
      - 8080:8080
    user: "1000:1000"
    volumes:
    - /:/rootfs:ro
    - /var/lib/my_docker/version-pack-data/community/docker:/rootfs/var/lib/docker:ro
    - /var/run:/var/run:ro
    - /etc:/etc:ro
    - /dev:/dev:ro
    - /sys:/sys:ro
    - /dev/disk/:/dev/disk:ro
    - /var/lib/docker:/var/lib/docker:ro
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
